### PR TITLE
Self-host GoatCounter script

### PR DESCRIPTION
**Pull request by fredrik-bakke**
Makes us self-host the GoatCounter script. Perhaps this will avoid some more tracker blockers. ~The hosted script is a minified version of the original one.~

Follow-up to #1035.

### CODE REVIEW

**Comment by fredrik-bakke** [comment]
I'm having trouble building the website locally due to a new version of Python 🤦‍♂️

**Comment by VojtechStep** [comment]
If we're pretty-printing the mangled script then maybe just include it in the original form. Also the ISC license notice from the original file has to be included at the top of the file.

**Comment by fredrik-bakke** [comment]
Oh, shoot, I thought I had pushed the change

**Review by VojtechStep — APPROVED** [review]
LGTM

**Pull request merged**
