### PR TITLE
The perfect core of a group

### PR DESCRIPTION
**Pull request by EgbertRijke**
This PR adds the predicate of being a perfect core.

### CODE REVIEW

**Review by fredrik-bakke — APPROVED** [review]
Nice and simple :)

**Comment by fredrik-bakke** [comment]
oops, I shouldn't have done that

**Comment by fredrik-bakke** [comment]
lol, that really wasn't intentional

**Comment by EgbertRijke** [comment]
No, don't feel bad about that. This is such a small PR it is not worth feeling bad about.

**Pull request merged**
