### PR TITLE
Rename `is-contr-total` to `is-torsorial`

### PR DESCRIPTION
**Pull request by EgbertRijke**
Since the definition of `is-torsorial` is that the total space is contractible, this pull request proposes to replace the clumsy-looking `is-contr-total` with `is-torsorial`.

### CODE REVIEW

**Comment by fredrik-bakke** [comment]
I have a concern that the term "torsorial" may be less known or intuitive, making the entries harder to find and understand in context. The phrasing "contr-total" is after all very descriptive and clear, although, as you put it, also perhaps clumsy-looking to someone who knows the more advanced terminology.

**Comment by EgbertRijke** [comment]
I'm glad you're saying that, especially in the context of the discussion about cotowers.

**Comment by fredrik-bakke** [comment]
I've made my case for why I think `cotower` is better elsewhere, and there's nuance to the subject that is worth discussing case by case. In either case, I'm not clearly against `torsorial`. Maybe it is just my own ignorance that has led to my concern. If we establish the terminology well enough, then this can just be an experience of learning for users who didn't know the term before rather than confusion.

**Review by fredrik-bakke — APPROVED** [review]

**Comment by EgbertRijke** [comment]
Btw, this pull request did simply a search-and-replace. So I would be ok with it if it gets rejected. But it's definitely worth discussing how much we want to use/avoid terminology that is mostly used in more advanced mathematics. Perhaps we can come up with some sort of guideline on when to use advanced terminology or when to avoid it.

(As I type this message, I see that you already merged it)

**Comment by EgbertRijke** [comment]
Now I think we can use cotower too:)

To the learning experience 🍻

**Comment by fredrik-bakke** [comment]
Cheers 🍻

(For real, I don't want this to be a bargaining game though)

**Pull request merged**
