### PR TITLE
Throw error when `{{#bibliography}}` is invoked with empty reference list

### LINKED ISSUE #1175: CI should error when `{{#bibliography}}` is invoked and there are no references
Cool development! Just wanted to mention that the [references](https://unimath.github.io/agda-unimath/synthetic-category-theory.synthetic-categories.html#references) are not displaying here.

_Originally posted by @FernandoChu in https://github.com/UniMath/agda-unimath/issues/1171#issuecomment-2325965980_

### PR DESCRIPTION
**Pull request by fredrik-bakke**
Fixes #1175.

### CODE REVIEW

**Comment by fredrik-bakke** [comment]
Hopefully `link-check` will throw an error on `synthetic-category-theory.synthetic-categories`. This PR should wait to be merged until after #1176.

**Comment by EgbertRijke** [comment]
Neat! Feel free to merge this after the other PR is merged

**Review by EgbertRijke — APPROVED** [review]

**Comment by fredrik-bakke** [comment]
Something is not right, it's supposed to throw an error but it isn't.

**Comment by VojtechStep** [comment]
What's wrong with this PR? I tried adding a `{{#bibliography}}` to a page without any `{{#cite}}`s or `{{#reference}}`s and it gives me an error as expected.

**Comment by fredrik-bakke** [comment]
Huh, that's weird, because the ci didn't throw an error when there was an empty bibliography in the synthetic-category-theory namespace module. I haven't marked this pr as mergable because I couldnt figure out how to debug the script locally again

**Comment by fredrik-bakke** [comment]
If you say it works, then I'm okay with merging.

**Comment by fredrik-bakke** [comment]
Does the CI not run the new version of the script until it is merged?

**Comment by VojtechStep** [comment]
I'm not really sure what you're asking. Would you expect a different PR to run this version of the citations script which only exists in this PR?

**Comment by fredrik-bakke** [comment]
My point is that in this run of the CI:

- https://github.com/UniMath/agda-unimath/actions/runs/10691214039/job/29637385023

the script should have thrown an error as there was an invocation of `{{#bibliography}}` that was empty, namely the one in `synthetic-category-theory` or `synthetic-category-theory.synthetic-categories`.

**Comment by VojtechStep** [comment]
The only time I see synthetic categories appear in this PR is with the 'merge master into fix-bibliography' commit, and at that point there are no dangling `{{#bibliography}}` tags. When that CI ran, was the dangling `{{#bibliography}}` call in this branch?

**Comment by fredrik-bakke** [comment]
My belief is that it was until that merge commit, yes.

**Comment by VojtechStep** [comment]
Oh I see. Could you push a file with the same error, just to check that it still doesn't work?

**Comment by fredrik-bakke** [comment]
> Oh I see. Could you push a file with the same error, just to check that it still doesn't work?

Sure, I added two. One in the `foundation` namespace file and the other in `foundation.0-connected-types`

**Comment by fredrik-bakke** [comment]
Ah, it works! Then let's merge 😁

**Comment by fredrik-bakke** [comment]
I'll wait to see if you have any interjections first, @VojtechStep.

**Comment by VojtechStep** [comment]
No interjections, thanks for the improvement 👌
I'm enabling automerge

**Pull request merged**
