### PR TITLE
Change file names + move comp-emb out of abstract block

### PR DESCRIPTION
**Pull request by elisabethbonnevier**

### CODE REVIEW

**Comment by EgbertRijke** [comment]
Can you add the unique-existence imports to README and foundation (in the correct spot with alphabetic ordering)

**Comment by elisabethbonnevier** [comment]
Sure :) (forgot to do make check before commiting)

**Comment by elisabethbonnevier** [comment]
I put it in foundation.lagda.md, but where do you want it in README? I don't see any imports there

**Comment by EgbertRijke** [comment]
It's a bit confusing that this file is also called readme.

**Comment by EgbertRijke** [comment]
Can you also put the imports that you changed in alphabetic order?

**Comment by elisabethbonnevier** [comment]
Ah, yes of course :) Done!

**Pull request merged**
