### PR TITLE
Feature additions – unused imports

### PR DESCRIPTION
**Pull request by fredrik-bakke**
- Make unused imports remover order files by git history to check the most relevant files first, even when moving between local branches
- Add ability to search specified files or folders
- Add vscode task to remove unused imports in current file

### CODE REVIEW

**Comment by EgbertRijke** [comment]
I can't really judge this code, but I am happy with the idea of this addition

**Comment by fredrik-bakke** [comment]
Then I think it's good to merge 😄

**Comment by EgbertRijke** [comment]
We got auto-merge on on the colocal pull request, so I'm going to turn this one off because it needs to be updated anyway

**Comment by EgbertRijke** [comment]
Ah, I didn't see that it just merged

**Comment by fredrik-bakke** [comment]
Oh, sorry about that

**Pull request merged**
