### PR TITLE
Rational addition and format for future work on rationals

### PR DESCRIPTION
**Pull request by shiranaiyo**
Refactored some stuff, importantly separating integer fractions from the rationals. My idea is that all future operations on rationals be defined on integer fractions first, and then carried to rationals; as working with the gcd directly is horrible. I did the first part of the additions to show how it'd look, I'd use this schema for the other operations and properties too.

I'd like confirmation that this approach is fine, though it duplicates the number of files.

### CODE REVIEW

**Comment by EgbertRijke** [comment]
These changes look good to me, overall.

In #546 I'm also refactoring many files of elementary number theory, including some files you have been working on here. Therefore I would like to merge this as soon as possible, so that I can resolve any conflicts.

**Comment by shiranaiyo** [comment]
Great! I think I may take some time to finish it though. I'd guess you won't touch the rationals so I think this could be merged to resolve any conflicts now. My changes from now on will touch only fractions and rationals, most likely. I'm marking it as ready for review then.

**Comment by shiranaiyo** [comment]
I realized real numbers could be define without further theory, so I did it, following HoTT book's dedekind real numbers.

I will rest for a week so you can merge now to avoid conflicts with https://github.com/UniMath/agda-unimath/pull/546, if you want.

**Comment by EgbertRijke** [comment]
That's very nice! Indeed, we were planning on following this route with the Dedekind real numbers, because it is the most straightforward in my opinion.

**Pull request merged**
