### PR TITLE
Compatibility patch for Agda 2.6.4

### PR DESCRIPTION
**Pull request by fredrik-bakke**
Makes the library compatible with Agda 2.6.4.

### CODE REVIEW

**Comment by fredrik-bakke** [comment]
In case you're listening, @FernandoChu, is there anything that has appeared in 2.6.4 to replace `AGDATCMBLOCKONMETA`?

**Comment by fredrik-bakke** [comment]
Alright, this one is ready for review now.

**Comment by EgbertRijke** [comment]
LGTM, Can I merge it?

**Comment by fredrik-bakke** [comment]
Please do!

**Pull request merged**
