### PR TITLE
Add missing references

### PR DESCRIPTION
**Pull request by fredrik-bakke**
These were a series of missing references in the old `src/README.lagda.md` that now when ported to the new website lead to missing pages.

I think for the scalability of this project, there should really be a job in the GitHub workflow that checks that the appropriate references are in place, as it's a recurring and tedious job to check this. I will make an issue on this later though.

Edit: The issue is now #448

### CODE REVIEW

**Comment by fredrik-bakke** [comment]
Im adding missing references to other namespaces as well, but have other obligations at the moment. Ill mark the PR as ready for review when it's done.

**Comment by fredrik-bakke** [comment]
I also formatted `SUMMARY.lagda.md` slightly differently. If this does not look good on the website, then I simply have to revert `07a2b9f`.

**Comment by EgbertRijke** [comment]
Since you made changes to Summary, I have asked Jonathan to look at this. I cannot see by looking at the code what it will do to the website.

**Comment by fredrik-bakke** [comment]
Thank you. I'll just leave it until he has a chance to review it :)

I expect that there may be an issue with having links in the headers in `SUMMARY.lagda.md`, as these already link to their position on the page. But we'll see.

**Comment by EgbertRijke** [comment]
You can build the website locally on your machine by running `make website`

**Comment by jonaprieto** [comment]
Indeed headers cannot have links, at least not in SUMMARY.lagda.md. If you don't mind, let me fix it here. The other changes look good to me.

**Comment by fredrik-bakke** [comment]
Alright, great! I tried `make website` but had this error:
```
make: mdbook: No such file or directory
```

**Comment by jonaprieto** [comment]
Did you install the tool `mdbook`? You must first install `cargo` and `cargo install mdbook`.
See here `https://doc.rust-lang.org/cargo/getting-started/installation.html`.

**Comment by fredrik-bakke** [comment]
I haven't done that, although I did assume I was missing some piece of software. And I agree with your second point.

**Comment by jonaprieto** [comment]
Oh, I forgot you pushed from your fork. Please pick the changes from this commit:
https://github.com/UniMath/agda-unimath/commit/714b6e6b3316ac4d2455a880d92b4d34d1dd00d0

**Comment by fredrik-bakke** [comment]
Sorry, I just went to bed. I'll look at it tomorrow!

**Comment by fredrik-bakke** [comment]
Hey! I see you've merged some of the commits now. Do you still want me to add 714b6e6 to this PR, or should it be closed?

**Comment by jonaprieto** [comment]
Yes, please do. I just rebase your PR to be updated with latest changes in the main branch.

**Comment by fredrik-bakke** [comment]
Sorry, you can ignore the collaboration invitation. I was just trying out to see if there was an easy way to give people access to commit to my PRs.

**Comment by fredrik-bakke** [comment]
Hey again, I'm struggling with keeping my tongue straight while merging these branches, and I fail to find any improvements in your branch aside from removing a single line break. Could you perhaps point out the fixes you did instead, so I can implement those instead of painstakingly reviewing and merging 19 commits, almost all of which are just the fixes I already implemented?

**Comment by fredrik-bakke** [comment]
I've looked over again, and it seems that indeed the only difference is that one line break and the fact your branch is out of sync. Am I missing something?

**Comment by jonaprieto** [comment]
It's fixed somehow, and it looks good now to me. I'll merge this.
Thanks!

**Comment by fredrik-bakke** [comment]
Ah, great! 😄

**Pull request merged**
