### PR TITLE
Countability results

### PR DESCRIPTION
**Pull request by ElifUskuplu**
I hope this PR is ready to review :)

The work is about some countability results and the proof of that `R` is set. Since the latter consists of only one file, I didn't want to open a seperate PR. Btw, I'll take a break from formalizing for a while to continue my own research.

This PR has:

* `R` is set
* Equivalent definition of countability
* Countability preserves product and coproduct
* `NxN` `N+N` `Z` `Fin n` are all countable
* type arithmetic for natural numbers
* any natural number can be written as `2^u(2v+1) - 1`
* auxiliary results about `exp-N`, divisibility, parity

### CODE REVIEW

**Comment by fredrik-bakke** [comment]
Hey Elif!
Last week Egbert reported in #551 that you had some issues with `pre-commit` when doing #549. I see the CI is happy with your PR this week. Did you by chance resolve the issue with `pre-commit` yourself?

**Comment by ElifUskuplu** [comment]
> Hey Elif! Last week Egbert reported in #551 that you had some issues with `pre-commit` when doing #549. I see the CI is happy with your PR this week. Did you by chance resolve the issue with `pre-commit` yourself?

Hi Fredrik, yes, I solved myself. This was because my .git directory was in wrong place. But sometimes `pre-commit` ignores and does not fixes some files. I don't know why?
Thanks for your interest.

**Comment by fredrik-bakke** [comment]
> > Hey Elif! Last week Egbert reported in #551 that you had some issues with `pre-commit` when doing #549. I see the CI is happy with your PR this week. Did you by chance resolve the issue with `pre-commit` yourself?
> 
> Hi Fredrik, yes, I solved myself. This was because my .git directory was in wrong place. But sometimes `pre-commit` ignores and does not fixes some files. I don't know why? Thanks for your interest.

I see. One reason that this may happen is if you've written a closing markdown tag ` ``` ` when you meant to write an opening markdown tag ` ```agda `. Has this happened to you in any other scenario?

**Comment by ElifUskuplu** [comment]
> > > Hey Elif! Last week Egbert reported in #551 that you had some issues with `pre-commit` when doing #549. I see the CI is happy with your PR this week. Did you by chance resolve the issue with `pre-commit` yourself?
> > 
> > 
> > Hi Fredrik, yes, I solved myself. This was because my .git directory was in wrong place. But sometimes `pre-commit` ignores and does not fixes some files. I don't know why? Thanks for your interest.
> 
> I see. One reason that this may happen is if you've written a closing markdown tag `` ``` `` when you meant to write an opening markdown tag `` ```agda ``. Has this happened to you in any other scenario?

Can you look at `src/elementary-number-theory/type-arithmetic-natural-numbers.lagda.md` file in this PR, please? I think there is no markdown issue. `pre-commit` ignored the order of imported modules, so I fixed manually.

**Comment by fredrik-bakke** [comment]
That's interesting. I tried this locally, and `pre-commit` did the correct thing on my machine. I may note that `pre-commit` only sorts import statements encased in a `<details>`-block. Did you by chance not have the `<details>` tags in your code when you first encountered this issue?

**Comment by ElifUskuplu** [comment]
> That's interesting. I tried this locally, and `pre-commit` did the correct thing on my machine. I may note that `pre-commit` only sorts import statements encased in a `<details>`-block. Did you by chance not have the `<details>` tags in your code when you first encountered this issue?

No, `<details>` tags were placed. I reversed two imported modules in the file locally in order to check again. And `pre-commit` again did not consider it. For a different file, however, it worked.

This file was in `foundation` directory initially. Then I moved it to `elementary-number-theory`, but edited related files accordingly. Can this be the reason?

**Comment by ElifUskuplu** [comment]
> > > That's interesting. I tried this locally, and `pre-commit` did the correct thing on my machine. I may note that `pre-commit` only sorts import statements encased in a `<details>`-block. Did you by chance not have the `<details>` tags in your code when you first encountered this issue?
> > 
> > 
> > No, `<details>` tags were placed. I reversed two imported modules in the file locally in order to check again. And `pre-commit` again did not consider it. For a different file, however, it worked.
> > This file was in `foundation` directory initially. Then I moved it to `elementary-number-theory`, but edited related files accordingly. Can this be the reason?
> 
> Hmm, this sounds very strange, and I'm unsure what the issue is here. One thing I'm curious about is if the problem persists if you run it in a completely clean repository. I.e. download your branch to a new folder and try again. If this resolves your issue, then that would suggest that something was wrong with your git setup.

I'll try and inform you, thanks.

**Comment by fredrik-bakke** [comment]
Oh, I just realized something else as well. When I cloned your branch and ran `make pre-commit`, the file `src/everything.lagda.md` was [changed quite substantially](https://github.com/fredrik-bakke/agda-unimath/commit/6f99a9447869f31699765a288f7e8734b811811a#diff-9e48793bed73aab4f26bf79f41f2c71e369f7db8eead84f07eeb3396cfa35424). This file is generated automatically as part of `make check`, and I'm unsure what may have caused this big discrepancy currently.

**Comment by ElifUskuplu** [comment]
> Oh, I just realized something else as well. When I cloned your branch and ran `make pre-commit`, the file `src/everything.lagda.md` was [changed quite substantially](https://github.com/fredrik-bakke/agda-unimath/commit/6f99a9447869f31699765a288f7e8734b811811a#diff-9e48793bed73aab4f26bf79f41f2c71e369f7db8eead84f07eeb3396cfa35424). This file is generated automatically as part of `make check`, and I'm unsure what may have caused this big discrepancy currently.

I've tried your suggestion and the same problem occured. And I realized that the problematic files are 'src/elementary-number-theory/powers-of-two.lagda.md` `src/elementary-number-theory/type-arithmetic-natural-numbers.lagda.md` and `src/everything.lagda.md`. The common point of first and second that I've created these first time, didn't obtained by editing an old file. As for third file, I don't get it because I didn't make any changes on it manually.

**Pull request merged**
