### PR TITLE
Swap from `md` to `text` code blocks

### PR DESCRIPTION
**Pull request by fredrik-bakke**
- Fix diagrams in `pullback-hom`
- Swap from `md` to `text` code blocks
- Register Collatz' bijection in the OEIS file

### CODE REVIEW

**Comment by EgbertRijke** [comment]
Cool! Did you compile the website locally to see whether it looks good?

**Comment by fredrik-bakke** [comment]
oh, uh, no. I don't know how to do that 😅

**Comment by fredrik-bakke** [comment]
But I also have to run, so can't do it now

**Comment by EgbertRijke** [comment]
No worries. I'm also travelling at the moment. The command for compiling the website is `make website`

**Comment by VojtechStep** [comment]
There's a make target to install the website dependencies, assuming you have Rust installed (it uses cargo): `make install-website-dev`. Then to build the website you run `make website`, and to open it you run `make serve-website` (it takes a second to start the web server, and IIRC then it should open up the page in your browser automatically).

This should probably be documented somewhere.

**Comment by fredrik-bakke** [comment]
image

Looks good to me! 😄 Thanks for the help, Vojtech!

**Pull request merged**
