### PR TITLE
Editing CSB and split-surjective files & Adding set theory folder

### PR DESCRIPTION
**Pull request by ElifUskuplu**
I've made changes as @jonaprieto suggested.

### CODE REVIEW

**Comment by EgbertRijke** [comment]
The preperation could be replaced by an import from `foundation/iterating-functions`.

**Comment by EgbertRijke** [comment]
In general, names should not refer to variables

**Comment by EgbertRijke** [comment]
Can you change the file name to make it all lower case? This is to avoid messing up the ordering in how the files are listed by `everything`

**Comment by ElifUskuplu** [comment]
> The preperation could be replaced by an import from `foundation/iterating-functions`.

I've made this.

**Pull request merged**
